podonos/podonos-pysdk

podonos/core/client.py, tests/single_eval_test.py
=> Param change & single eval test

podonos/__init__.py, pyproject.toml
=> [Chore] Update sdk version into 0.2.1

podonos/core/evaluator.py, podonos/evaluators/double_stimuli_evaluator.py, podonos/evaluators/single_stimulus_evaluator.py, tests/test_double_stimuli_evaluator.py, tests/test_single_stimulus_evaluator.py
close #138 
`add_files` was not working in the evaluation type `PREF`, `SMOS`
=> [Fix] Type checking and fix logic of checking valid types when creating evaluation

History.md, podonos/__init__.py, pyproject.toml
close #140 
Fix the bug of `add_files` and `get_stats_dict_by_id`
=> [Chore] Update version into 0.2.2

podonos/core/config.py
=> [Fix] Send auto_start field to API

History.md, podonos/__init__.py, pyproject.toml
close #148 
- Remove `set_question` because the custom query is done in web
- Fix the auto_start option in evaluation
=> [Chore] Update version into 0.3.0

podonos/core/evaluator.py
=> [Feature] Split files into chunk per 500

History.md, podonos/__init__.py, pyproject.toml
=> [Docs] Upgrade version into 0.4.0

podonos/core/file.py
=> [Fix] Remove the duplicate tags

History.md, podonos/__init__.py, pyproject.toml
Remove the duplicate tags per file
=> [Feature] Update SDK Version into 0.5.0

podonos/common/enum.py, podonos/core/api.py, podonos/core/client.py, podonos/core/config.py, podonos/core/evaluation.py, podonos/core/evaluator.py, podonos/core/template.py, podonos/evaluators/double_stimuli_evaluator.py, podonos/evaluators/single_stimulus_evaluator.py, tests/test_api_client.py, tests/test_client.py, tests/test_config.py, tests/test_double_stimuli_evaluator.py, tests/test_evaluator.py, tests/test_sdk.py, tests/test_single_stimulus_evaluator.py
close #157 
- The main feature is that customers can create an evaluation from an existing template. 
- The new evaluation type is added ex) `CUSTOM_SINGLE`, `CUSTOM_DOUBLE` it doesn't create no question
=> [Feature] Create an evaluation from template

History.md, podonos/__init__.py, pyproject.toml
close #159 
- `create_evaluator_from_template`: Creating evaluation from template's unique code
- `create_evaluator`: The CUSTOM_SINGLE and CUSTOM_DOUBLE are supported
=> [Docs] Update version into 0.6.0

History.md, podonos/__init__.py, pyproject.toml
=> [Docs] Update version into 0.7.0

podonos/common/util.py, podonos/core/api.py, podonos/core/audio.py, podonos/core/evaluator.py, podonos/core/file.py, podonos/core/upload_manager.py, podonos/service/evaluation_service.py, tests/core/test_audio.py, tests/core/test_upload_manager.py
close #173 
The type is directly related with database so it should be checked before uploading files.
=> [Feature] Change tags type into string and checking type before uploading

podonos/core/api.py, tests/core/test_api.py
=> [Refactor] Change API for verifying API Key

History.md, podonos/__init__.py, pyproject.toml
close #177 
- Change the API key verification method
- Remove `SingleStimlusEvaluator` and `DoubleStimlusEvaluator`
- Create `EvaluationService` class for managing evaluations
=> [Docs] Update version into 0.8.0

History.md, podonos/__init__.py, pyproject.toml
close #183 
- Handle the error of `get_audio_info` when using `soundfile` library
=> [Docs] Upgrade version into 0.8.1

podonos/common/enum.py, podonos/core/api.py, podonos/core/client.py, podonos/core/query.py, podonos/core/template.py, podonos/core/types.py, podonos/service/template_service.py, tests/core/test_client.py, tests/core/test_query.py, tests/core/test_template.py, tests/service/test_template_service.py
close #185 
The feature between web and SDK is unsynchronized so it is hard to match the parameter's value. So the keyword is changed by understanding the parameter more easily  
Also, `reference_file` can be injected into `instruction` and `option` for help evaluators to make better decision
=> [Feature] Change interface of creating template and allow sdk to create reference file

History.md, podonos/__init__.py, pyproject.toml
close #187 
- Create `TemplateService` for interacting template
- Change interface of JSON used in `create_evaluator_from_template_json`
=> [Docs] Upgrade version into 0.9.0

podonos/core/client.py, podonos/core/template.py, tests/core/test_template.py, tests/service/test_template_service.py
=> [Feature] Remove use_annotation in create_evaluator_from_template

History.md, podonos/__init__.py, pyproject.toml
close #191 
- Remove `use_annotation` option in `create_evaluator_from_template`
=> [Docs] Update version into 0.10.0

podonos/common/enum.py, podonos/core/client.py, podonos/core/config.py, podonos/core/evaluator.py, podonos/entity/evaluation.py, podonos/evaluation/__init__.py, podonos/evaluation/ai_evaluation.py, podonos/evaluation/human_evaluation.py, podonos/service/ai_evaluation_service.py, podonos/service/evaluation_service.py, tests/core/test_evaluator.py, tests/entity/test_evaluation_entity.py, tests/service/test_ai_evaluation_service.py, tests/service/test_evaluation_service.py
close #193 
Podonos wants to provide voice analysis through ASR to provide customers with a richer evaluation service.
``` python
class Podonos:
def create_ai_evaluator(self) -> None:
evaluator = self.client.AI.asr(
name="ASR Evaluation Test by create_ai_evaluator",
lan="en-us",
)
for i in range(20):
file = File(path=f"path/file.wav", model_tag=<model_tag>, tags=<tags>, script=<script>)
evaluator.add_file(file)
evaluator.close()
```
=> [Feature] Create AI Evaluation of ASR

podonos/core/stimulus_stats.py, podonos/service/evaluation_service.py, tests/core/test_client.py
close #198 
```
{
"question": {
"title": "Single choice without value",
"order": 3
},
"files": [
{
"name": "./google/67-f-v.mp3",
"model_tag": "Google TTS",
"tags": [
"female",
"vivid"
],
"type": "A"
},
{
"name": "./resemble/67-f-v.wav",
"model_tag": "Resemble AI",
"tags": [
"female",
"vivid"
],
"type": "B"
}
],
"options": {
"OTHER": [],
"3": 3,
"1": 1
}
}
```
=> [Fix] Add selected options of multiple choice's question

History.md, podonos/__init__.py, podonos/core/query.py, pyproject.toml
close #197 
- Fix the bug of `get_stats_by_evaluator` (`OTHER` is not included in the stats)
- Add `anchor_label` in `create_evaluator_from_template_json`
=> [Docs] Update sdk version into 0.11.0

podonos/core/client.py
=> [Fix] Add num_eval default value 10

History.md, podonos/__init__.py, pyproject.toml
close #205 
- Support `CSMOS` for evaluation
- Add `num_eval`'s default value in `create_evaluator_from_template`
=> [Docs] Update version into 0.12.0

History.md, podonos/__init__.py, podonos/core/client.py, podonos/service/evaluation_service.py, pyproject.toml, tests/service/test_evaluation_service.py
close #207 
- Add `group_by` option in `get_stats_dict_by_id`
=> [Feature] Update version and get stats by evaluation_id by group

History.md, podonos/__init__.py, podonos/core/client.py, podonos/service/evaluation_service.py, pyproject.toml, tests/core/test_client.py, tests/integration/integration_test_all.py, tests/service/test_evaluation_service.py
close #209 
- Remove `download_stats_csv_by_id`
- Rename `get_stats_dict_by_id` into `get_stats_json_by_id`
=> [Feature] Remove download_csv_by_id and rename function

podonos/common/enum.py, podonos/core/query.py, podonos/core/template.py, podonos/core/types.py, tests/core/test_query.py
close #211 
The question can be connected with specific model
=> [Feature] Support related_model in SDK

podonos/core/file.py
=> [Feature] Allow only two models in double stimulus

History.md, podonos/__init__.py, pyproject.toml
close #215 
- Select the `related_model` when creating `Evaluation` in `template`
=> [Docs] Upgrade version into 0.15.0

podonos/common/constant.py, podonos/core/client.py, podonos/service/evaluation_service.py, tests/service/test_evaluation_service.py
=> [Feature] Download_evaluation_files_by_evaluation_id

History.md, podonos/__init__.py, pyproject.toml
close #219 
- Get evaluation files by `download_evaluation_files_by_evaluation_id`
=> [Docs] Update the version into 0.16.0

podonos/common/enum.py, podonos/core/client.py, podonos/core/script.py, podonos/entity/script.py, podonos/service/__init__.py, podonos/service/collection_service.py, podonos/service/script_service.py, tests/service/test_script_service.py
close #223 
Create and get all scripts
```python3
client = podonos.init()
client.script.create_all(collection_id, ["test", "test1"])
client.script.list(collection_id)
```
=> [Feature] Create and Get all scripts

podonos/common/enum.py, podonos/core/file.py, podonos/evaluation/human_evaluation.py
close #225 
It is possible to create CSMOS evaluation by `create_evaluator_from_template`
=> [Feature] Create CSMOS template evaluator

History.md, podonos/__init__.py, pyproject.toml
close #227 
- Implement data collection feature
- Support Create evalautor from CSMOS template
=> [Docs] Update version into 0.17.0

podonos/common/enum.py, podonos/core/client.py, podonos/core/config.py, podonos/core/file.py, podonos/core/template.py, podonos/evaluation/ai_evaluation.py, podonos/evaluation/human_evaluation.py, tests/core/test_config.py, tests/core/test_template.py, tests/service/test_ai_evaluation_service.py, tests/service/test_template_service.py
=> [Feature] Add auto analysis option when creating an evaluation

History.md, podonos/__init__.py, pyproject.toml
close #231 
- Support `use_auto_analysis` option in evaluator
=> [Docs] Upgrade version into 0.18.0

podonos/common/enum.py, podonos/core/config.py, podonos/core/file.py, podonos/evaluation/human_evaluation.py
close #233 
`CMOS` is only supported in `create_evaluator`
=> [Feature] Create CMOS evaluator

History.md, podonos/__init__.py, pyproject.toml
close #235 
- Support `CMOS` evaluation type
=> [Docs] Update SDK version into 0.19.0

podonos/core/client.py, podonos/core/template.py, podonos/evaluation/human_evaluation.py, tests/core/test_client.py, tests/core/test_template.py
=> [Refactor] Remove use_annotation and use_power_normalization in Template

podonos/common/enum.py, podonos/core/client.py, podonos/core/collection.py, podonos/core/config.py, podonos/core/file.py, podonos/core/script.py, podonos/core/stimulus_stats.py, podonos/core/template.py, podonos/core/types.py, podonos/entity/collection.py, podonos/entity/evaluation.py, podonos/entity/script.py, podonos/evaluation/human_evaluation.py, podonos/service/evaluation_service.py, tests/common/test_enum.py, tests/core/test_client.py, tests/core/test_collection.py, tests/core/test_config.py, tests/service/test_ai_evaluation_service.py, tests/service/test_collection_service.py, tests/service/test_evaluation_service.py, tests/test_sdk.py
close #250 
- Added en-IN screen set integration
- Updated evaluation API wrapper to handle Indian language codes
- Added unit tests for en-IN evaluations
=> [Feature] Add support for en in language evaluations in sdk

History.md, podonos/__init__.py, pyproject.toml
closes #252
- Added en-in language support to evaluations
- Updated Language enum with ENGLISH_INDIA = "en-in"
- Added tests for en-IN functionality
- Improved Python 3.8+ compatibility
=> [Docs] Update version into 0.24.0
